vich_uploader:
    db_driver: orm
# producte uploader 
    mappings:
        product_images:
            uri_prefix: /uploads/products
            upload_destination: '%kernel.project_dir%/public/uploads/products'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
# restaurant uploader 
        restaurant_images:
            uri_prefix: /uploads/restaurants
            upload_destination: '%kernel.project_dir%/public/uploads/restaurants'
            namer: Vich\UploaderBundle\Naming\UniqidNamer