controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_about_us:
    path: /a-propos-de-nous
    controller: App\Controller\InfoController::aboutUs

app_privacy_policy:
    path: /politique-de-confidentialite
    controller: App\Controller\InfoController::privacyPolicy

app_legal_mentions:
    path: /mentions-legales
    controller: App\Controller\InfoController::legalMentions

app_terms_of_use:
    path: /conditions-utilisation
    controller: App\Controller\InfoController::termsOfUse

app_terms_of_sale:
    path: /conditions-vente
    controller: App\Controller\InfoController::termsOfSale
